const menu = [
    {
      id: 1,
      title: 'Arepas',
      category: 'breakfast',
      time: 30,
      img: 'images/arepas.jpeg',
      desc: 'Traditional Colombian corn cakes',
      ingredients: "water, cornmeal, salt, oil, cheese (optional)",
      steps: [`Pour cornmeal into a bowl.`,
      `Add water to make cornmeal into a paste.`, 
      `Mix with hands until cornmeal is
      a thick paste.`,`Optional: add shredded cheese to mix.`,
      `Add salt to paste and mix.`, 
      `Round medium amount of cornmeal into a ball and then flatten into a thick cake.`, 
      `Apply small amount of oil in a pan and heat on 5 (medium).`, 
      `Place cake on pan and cook until golden brown on each side`, 
      `Add butter.`, 
      `Enjoy!`]    
    },
    {
      id: 2,
      title: 'Spaghetti',
      category: 'dinner',
      time: 20,
      img: 'images/spaghetti.jpg',
      desc: "Classic italian dish",
      ingredients: "spaghetti, water, salt, pepper, pasta sauce, onions, red pepper, oil, spinach, garlic powder, cheese",
      steps: ['Boil water inside of a large pot',
      `Add pasta to the water once it is boiling`,
      `Stir occasionally to avoid pasta sticking`,
      `Cook pasta until soft`,
      `Drain water from pasta`,
      `Cut onions and red pepper into thin slices.`,
      `In a pan pour teaspoon of oil and then the onions and peppers.`,
      `Cook until golden color on medium heat (5).`, 
      `Cut spinach into chunks and add to pan with onions and peppers. Cook for 2 minutes.`, 
      `Pour ingredients from pan into the pasta pot.`,
      `Add pasta sauce`,
      `Add salt, pepper, and garlic powder`,
      `Mix well and cook on medium heat for 5 minutes`,
      `Once cooked, add desired cheese`,
      `Enjoy!`]
    }, 
    {
      id: 3,
      title: 'Fish Tacos and Fries',
      category: 'dinner',
      time: 25,
      img: 'images/fishtacos.jpeg',
      desc: "Tacos and fries",
      ingredients: "Tilapia fillets, tortillas (hard or soft), lettuce, onion, fries, salsa, avocado",
      steps: ['Microwave fillets for 1 minute to defrost. Rinse afterward.',
      `Onions: remove top layer, cut out 1/5, cut into thin slices.`,
      `Lettuce: Remove top layer, chop into slices.`,
      `Fries: Heat oil for about 3 minutes on medium heat, or airfry for 15 minutes.`,
      `Add fries to oil, cook until golden.`,
      `Tortillas: warm on medium heat until light brown`,
      `Fillets: chop fish into small strips, season with salt and garlic, fry chunks on medium until golden/crispy.`, 
      `Add fish, onions, and lettuce to tortillas.`, 
      `Add desired toppings (salsa, cheese, avocado slices)`, 
      `Enjoy!`]},
    {
      id: 4,
      title: 'Cream of Mushroom',
      category: 'dinner',
      time: 35,
      img: 'images/creamofmushroom.jpeg',
      desc: "Tacos and fries",
      ingredients: "Water, 1/5 onion, 1 stick of celery, mushrooms (4 for two bowls), butter, table cream(optional), garlic powder, salt, black pepper, flour.",
      steps: ['Separate onion into layers, cut celery stick into a few shorter pieces, cut mushrooms into pieces.',
      `Add water to pot half way, add: onion, mushrooms, celery, garlic powder, salt, pepper, and boil on medium.`,
      `Lettuce: Remove top layer, chop into slices.`,
      `When boiling, turn off heat, and wait 5 minutes for mix to cool.`,
      `Pour most of the mix into blender, leaving 2 cups of boiling water with no content.`,
      `Pour water into a bowl and add 1 spoonful of flour. Mix well until no clumps are visible.`,
      `Pour blended mix back into pot, add the flour mix as well.`, 
      `Mix well and heat to on low, stirring to avoid clumps.`, 
      `Wait for mix to react with flour (it thickens), taste to see if more salt, pepper or garlic is needed.`, 
      `Note: If too thick, add water and continue cooking until desired thickness.`,
      `If too liquid, add 1/2 spoon of flour to water.`,
      `Repeat steps if necessary.`,
      `Add 1 spoonful of butter`,
      `Add 1-2 spoonfuls of table cream`,
      `Mix well.`
      `Enjoy!`]}
  ];
  export default menu;
  